### ISSUE TITLE
Example of running in Docker Compose based setup?

### ISSUE THREAD

**Issue by epugh** [CtrlSpice/otel-desktop-viewer#148]
I'm trying to run in a Docker compose environment.  My Dockerfile looks like:
```
FROM golang:bullseye

RUN go install github.com/CtrlSpice/otel-desktop-viewer@v0.1.4

CMD ["otel-desktop-viewer", "--browser", "7002"]

```

And Docker Compose:
```
  otel_desktop_viewer:
    container_name: otel_desktop_viewer
    build: ./otel-desktop-viewer
    #network_mode: host
    ports:
      - "7002:7002" # web ui
      - "4318:4318" # otel http
      - "4317:4317" # otel grpc
      - "8888:8888" # prometheus
```

In the logs it says it fired up, but I can't connect from the browser...   http://localhost:7002 just gives a stnadard "connection reset".  Has anyone else done this?   

I installed via Brew and everything worked ;-)
